#include "citygml/writers/obj_writer.h"
#include <fstream>
#include <iomanip>
#include <sstream>
#include <cctype>

namespace {

static std::string makeValidMtlName(const std::string& name, int index) {
    if (name.empty()) {
        std::ostringstream ss;
        ss << "mat_" << index;
        return ss.str();
    }
    std::string result;
    result.reserve(name.size());
    for (char c : name) {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_' || c == '-' || c == '.') {
            result += c;
        } else {
            result += '_';
        }
    }
    return result;
}

} // anonymous namespace

namespace citygml {

// Write .mtl file content from a list of materials.
static void writeMtlFile(std::ostream& out, const std::vector<std::pair<std::string, Material>>& materials) {
    out << "# MTL file generated by citygml-to-obj\n\n";
    for (const auto& [name, mat] : materials) {
        out << "newmtl " << name << "\n";
        out << std::fixed << std::setprecision(6);
        out << "Kd " << mat.diffuseR << " " << mat.diffuseG << " " << mat.diffuseB << "\n";
        out << "Ka " << mat.ambientR << " " << mat.ambientG << " " << mat.ambientB << "\n";
        if (mat.specularR != 0.0 || mat.specularG != 0.0 || mat.specularB != 0.0) {
            out << "Ks " << mat.specularR << " " << mat.specularG << " " << mat.specularB << "\n";
        }
        if (mat.shininess > 0.0) {
            out << "Ns " << mat.shininess << "\n";
        }
        if (mat.transparency > 0.0) {
            out << "d " << (1.0 - mat.transparency) << "\n";
            out << "Tr " << mat.transparency << "\n";
        }
        if (!mat.textureURI.empty()) {
            out << "map_Kd " << mat.textureURI << "\n";
        }
        out << "\n";
    }
}

bool writeObjFile(const Mesh& mesh, const std::string& objPath, const std::string& mtlPath) {
    return writeObjFile(std::vector<Mesh>{mesh}, objPath, mtlPath);
}

bool writeObjFile(const std::vector<Mesh>& meshes, const std::string& objPath, const std::string& mtlPath) {
    if (meshes.empty()) return false;

    std::ofstream objOut(objPath);
    if (!objOut) return false;

    objOut << "# OBJ file generated by citygml-to-obj\n";
    objOut << "# Source: CityGML data\n\n";
    objOut << "mtllib " << mtlPath << "\n\n";

    // Collect all materials for .mtl file.
    std::vector<std::pair<std::string, Material>> allMaterials;
    std::vector<std::pair<size_t, std::string>> matIndexToName; // (material_index, mtl_name)

    uint64_t vertexOffset = 1;  // OBJ indices start at 1

    for (size_t mi = 0; mi < meshes.size(); ++mi) {
        const Mesh& mesh = meshes[mi];

        objOut << "# Object: " << (mesh.name.empty() ? "unnamed" : mesh.name) << "\n";
        objOut << "o " << (mesh.name.empty() ? "mesh" : mesh.name) << "\n";

        // Flatten all submeshes to get global vertex/index lists.
        std::vector<Vertex> allVerts;
        std::vector<Triangle> allTris;
        mesh.flatten(allVerts, allTris);

        // Count how many vertices have UV.
        size_t uvVertCount = 0;
        std::vector<size_t> vtIndex(allVerts.size(), 0);
        for (size_t i = 0; i < allVerts.size(); ++i) {
            if (allVerts[i].uv.has_value()) {
                vtIndex[i] = ++uvVertCount;
            }
        }
        bool hasAnyUV = (uvVertCount > 0);

        // Write vertices.
        objOut << std::fixed << std::setprecision(6);
        for (const Vertex& v : allVerts) {
            objOut << "v " << v.position.x << " " << v.position.y << " " << v.position.z << "\n";
        }
        objOut << "# " << allVerts.size() << " vertices\n";

        // Write texture coordinates only for vertices that have UV.
        if (hasAnyUV) {
            for (size_t i = 0; i < allVerts.size(); ++i) {
                if (allVerts[i].uv.has_value()) {
                    objOut << "vt " << allVerts[i].uv->u << " " << allVerts[i].uv->v << "\n";
                }
            }
        }
        objOut << "# " << uvVertCount << " texture coords\n";

        // Write normals.
        for (const Vertex& v : allVerts) {
            if (v.normal.length() > 1e-6) {
                objOut << "vn " << v.normal.x << " " << v.normal.y << " " << v.normal.z << "\n";
            } else {
                objOut << "vn 0 0 1\n";
            }
        }
        objOut << "# " << allVerts.size() << " normals\n";

        // Write faces grouped by submesh.
        size_t vertBase = 0;
        for (const SubMesh& sm : mesh.subMeshes) {
            // Assign material.
            std::string mtlName;
            bool found = false;
            for (const auto& [n, m] : allMaterials) {
                if (m.textureURI == sm.material.textureURI &&
                    m.diffuseR == sm.material.diffuseR &&
                    m.diffuseG == sm.material.diffuseG &&
                    m.diffuseB == sm.material.diffuseB) {
                    mtlName = n;
                    found = true;
                    break;
                }
            }
            if (!found) {
                mtlName = makeValidMtlName(sm.material.name.empty() ? sm.material.textureURI : sm.material.name,
                                            static_cast<int>(allMaterials.size()));
                allMaterials.emplace_back(mtlName, sm.material);
            }
            objOut << "usemtl " << mtlName << "\n";

            for (const Triangle& tri : sm.triangles) {
                uint64_t i0 = vertexOffset + vertBase + tri.v0;
                uint64_t i1 = vertexOffset + vertBase + tri.v1;
                uint64_t i2 = vertexOffset + vertBase + tri.v2;
                if (hasAnyUV) {
                    // f v/vt/vn format — vt index is 0 (no UV) or the 1-based index in the vt list.
                    uint64_t t0 = vertexOffset + vtIndex[vertBase + tri.v0];
                    uint64_t t1 = vertexOffset + vtIndex[vertBase + tri.v1];
                    uint64_t t2 = vertexOffset + vtIndex[vertBase + tri.v2];
                    objOut << "f " << i0 << "/" << t0 << "/" << i0 << " "
                           << i1 << "/" << t1 << "/" << i1 << " "
                           << i2 << "/" << t2 << "/" << i2 << "\n";
                } else {
                    objOut << "f " << i0 << "//" << i0 << " "
                           << i1 << "//" << i1 << " "
                           << i2 << "//" << i2 << "\n";
                }
            }
            vertBase += sm.vertices.size();
        }

        vertexOffset += allVerts.size();
        objOut << "\n";
    }

    objOut.close();

    // Write .mtl file.
    std::ofstream mtlOut(mtlPath);
    if (!mtlOut) return false;
    writeMtlFile(mtlOut, allMaterials);
    mtlOut.close();

    return true;
}

} // namespace citygml
