#include "obj_writer.h"
#include <fstream>
#include <iomanip>
#include <sstream>
#include <cctype>
#include <algorithm>

namespace {

static std::string makeValidMtlName(const std::string& name, int index) {
    if (name.empty()) {
        std::ostringstream ss;
        ss << "mat_" << index;
        return ss.str();
    }
    std::string result;
    result.reserve(name.size());
    for (char c : name) {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_' || c == '-' || c == '.') {
            result += c;
        } else {
            result += '_';
        }
    }
    return result;
}

static void writeMtlFile(std::ostream& out,
                         const std::vector<std::pair<std::string, citygml::Material>>& materials) {
    out << "# MTL file generated by citygml-to-obj\n\n";
    for (const auto& [name, mat] : materials) {
        out << "newmtl " << name << "\n";
        out << std::fixed << std::setprecision(6);
        out << "Kd " << mat.diffuseR << " " << mat.diffuseG << " " << mat.diffuseB << "\n";
        out << "Ka " << mat.ambientR << " " << mat.ambientG << " " << mat.ambientB << "\n";
        if (mat.specularR != 0.0 || mat.specularG != 0.0 || mat.specularB != 0.0) {
            out << "Ks " << mat.specularR << " " << mat.specularG << " " << mat.specularB << "\n";
        }
        if (mat.shininess > 0.0) {
            out << "Ns " << mat.shininess << "\n";
        }
        if (mat.transparency > 0.0) {
            out << "d " << (1.0 - mat.transparency) << "\n";
            out << "Tr " << mat.transparency << "\n";
        }
        if (!mat.textureURI.empty()) {
            out << "map_Kd " << mat.textureURI << "\n";
        }
        out << "\n";
    }
}

static std::string extractBasename(const std::string& path) {
    size_t pos = path.find_last_of("/\\");
    if (pos == std::string::npos) return path;
    return path.substr(pos + 1);
}

static bool doWriteObj(std::ostream& objOut,
                       std::vector<std::pair<std::string, citygml::Material>>& allMaterials,
                       const std::vector<citygml::Mesh>& meshes,
                       const std::string& mtlBasename,
                       const citygml::Vec3& offset) {
    objOut << "# OBJ file generated by citygml-to-obj\n";
    objOut << "# Source: CityGML data\n";
    objOut << "# Offset: " << std::fixed << std::setprecision(6)
           << offset.x << " " << offset.y << " " << offset.z << "\n\n";
    objOut << "mtllib " << mtlBasename << "\n\n";

    uint64_t vertexOffset = 1;

    for (size_t mi = 0; mi < meshes.size(); ++mi) {
        const citygml::Mesh& mesh = meshes[mi];

        objOut << "# Object: " << (mesh.name.empty() ? "unnamed" : mesh.name) << "\n";
        objOut << "o " << (mesh.name.empty() ? "mesh" : mesh.name) << "\n";

        std::vector<citygml::Vertex> allVerts;
        std::vector<citygml::Triangle> allTris;
        mesh.flatten(allVerts, allTris);

        size_t uvVertCount = 0;
        std::vector<size_t> vtIndex(allVerts.size(), 0);
        for (size_t i = 0; i < allVerts.size(); ++i) {
            if (allVerts[i].uv.has_value()) {
                vtIndex[i] = ++uvVertCount;
            }
        }
        bool hasAnyUV = (uvVertCount > 0);

        objOut << std::fixed << std::setprecision(6);
        for (const citygml::Vertex& v : allVerts) {
            objOut << "v " << (v.position.x - offset.x) << " "
                   << (v.position.y - offset.y) << " "
                   << (v.position.z - offset.z) << "\n";
        }
        objOut << "# " << allVerts.size() << " vertices\n";

        if (hasAnyUV) {
            for (size_t i = 0; i < allVerts.size(); ++i) {
                if (allVerts[i].uv.has_value()) {
                    objOut << "vt " << allVerts[i].uv->u << " " << allVerts[i].uv->v << "\n";
                }
            }
        }
        objOut << "# " << uvVertCount << " texture coords\n";

        for (const citygml::Vertex& v : allVerts) {
            if (v.normal.length() > 1e-6) {
                objOut << "vn " << v.normal.x << " " << v.normal.y << " " << v.normal.z << "\n";
            } else {
                objOut << "vn 0 0 1\n";
            }
        }
        objOut << "# " << allVerts.size() << " normals\n";

        size_t vertBase = 0;
        for (const citygml::SubMesh& sm : mesh.subMeshes) {
            std::string mtlName;
            bool found = false;
            for (const auto& [n, m] : allMaterials) {
                if (m.textureURI == sm.material.textureURI &&
                    m.diffuseR == sm.material.diffuseR &&
                    m.diffuseG == sm.material.diffuseG &&
                    m.diffuseB == sm.material.diffuseB) {
                    mtlName = n;
                    found = true;
                    break;
                }
            }
            if (!found) {
                mtlName = makeValidMtlName(sm.material.name.empty() ? sm.material.textureURI : sm.material.name,
                                            static_cast<int>(allMaterials.size()));
                allMaterials.emplace_back(mtlName, sm.material);
            }
            objOut << "usemtl " << mtlName << "\n";

            for (const citygml::Triangle& tri : sm.triangles) {
                uint64_t i0 = vertexOffset + vertBase + tri.v0;
                uint64_t i1 = vertexOffset + vertBase + tri.v1;
                uint64_t i2 = vertexOffset + vertBase + tri.v2;
                if (hasAnyUV) {
                    uint64_t t0 = vertexOffset + vtIndex[vertBase + tri.v0];
                    uint64_t t1 = vertexOffset + vtIndex[vertBase + tri.v1];
                    uint64_t t2 = vertexOffset + vtIndex[vertBase + tri.v2];
                    objOut << "f " << i0 << "/" << t0 << "/" << i0 << " "
                           << i1 << "/" << t1 << "/" << i1 << " "
                           << i2 << "/" << t2 << "/" << i2 << "\n";
                } else {
                    objOut << "f " << i0 << "//" << i0 << " "
                           << i1 << "//" << i1 << " "
                           << i2 << "//" << i2 << "\n";
                }
            }
            vertBase += sm.vertices.size();
        }

        vertexOffset += allVerts.size();
        objOut << "\n";
    }

    return true;
}

} // anonymous namespace

namespace citygml {

bool writeObjFile(const Mesh& mesh, const std::string& objPath, const std::string& mtlPath) {
    return writeObjFile(std::vector<Mesh>{mesh}, objPath, mtlPath);
}

Vec3 computeBoundingBoxCenter(const std::vector<Mesh>& meshes) {
    double minX = 0, minY = 0, minZ = 0;
    double maxX = 0, maxY = 0, maxZ = 0;
    bool first = true;

    for (const Mesh& mesh : meshes) {
        std::vector<Vertex> allVerts;
        std::vector<Triangle> allTris;
        mesh.flatten(allVerts, allTris);

        for (const Vertex& v : allVerts) {
            if (first) {
                minX = maxX = v.position.x;
                minY = maxY = v.position.y;
                minZ = maxZ = v.position.z;
                first = false;
            } else {
                if (v.position.x < minX) minX = v.position.x;
                if (v.position.y < minY) minY = v.position.y;
                if (v.position.z < minZ) minZ = v.position.z;
                if (v.position.x > maxX) maxX = v.position.x;
                if (v.position.y > maxY) maxY = v.position.y;
                if (v.position.z > maxZ) maxZ = v.position.z;
            }
        }
    }

    if (first) return {0, 0, 0};
    return {(minX + maxX) * 0.5, (minY + maxY) * 0.5, (minZ + maxZ) * 0.5};
}

bool writeObjFile(const std::vector<Mesh>& meshes,
                  const std::string& objPath,
                  const std::string& mtlPath)
{
    if (meshes.empty()) return false;
    Vec3 offset = computeBoundingBoxCenter(meshes);
    return writeObjFile(meshes, objPath, mtlPath, offset);
}

bool writeObjFile(const std::vector<Mesh>& meshes,
                  const std::string& objPath,
                  const std::string& mtlPath,
                  const Vec3& offset)
{
    if (meshes.empty()) return false;

    std::ofstream objOut(objPath);
    if (!objOut) return false;

    std::vector<std::pair<std::string, Material>> allMaterials;
    if (!doWriteObj(objOut, allMaterials, meshes, extractBasename(mtlPath), offset)) {
        return false;
    }
    objOut.close();

    std::ofstream mtlOut(mtlPath);
    if (!mtlOut) return false;
    writeMtlFile(mtlOut, allMaterials);
    mtlOut.close();

    return true;
}

bool writeObjFile(const std::vector<Mesh>& meshes,
                  const std::string& objPath,
                  const Vec3& offset)
{
    if (meshes.empty()) return false;

    std::string mtlPath = objPath;
    size_t dot = mtlPath.find_last_of('.');
    if (dot != std::string::npos && dot > mtlPath.find_last_of("/\\")) {
        mtlPath = mtlPath.substr(0, dot) + ".mtl";
    } else {
        mtlPath = mtlPath + ".mtl";
    }

    std::ofstream objOut(objPath);
    if (!objOut) return false;

    std::vector<std::pair<std::string, Material>> allMaterials;
    if (!doWriteObj(objOut, allMaterials, meshes, extractBasename(mtlPath), offset)) {
        return false;
    }
    objOut.close();

    std::ofstream mtlOut(mtlPath);
    if (!mtlOut) return false;
    writeMtlFile(mtlOut, allMaterials);
    mtlOut.close();

    return true;
}

} // namespace citygml
